# ── Stage 1: Install dependencies ────────────────────────────────────────────
FROM node:22-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# ── Stage 2: Build Next.js app ────────────────────────────────────────────────
FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate Prisma Client from schema (no DB connection needed)
RUN npx prisma generate

ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# ── Stage 3: Migrate runner ───────────────────────────────────────────────────
# Separate stage used by docker-compose to run `prisma migrate deploy`
# before the app starts. Keeps migration logic out of the app image.
FROM node:22-alpine AS migrator
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY prisma        ./prisma
COPY prisma.config.ts ./prisma.config.ts
COPY tsconfig.json    ./tsconfig.json
COPY package.json     ./package.json

CMD ["npx", "prisma", "migrate", "deploy"]

# ── Stage 4: Production runner ────────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Standalone Next.js server (self-contained, no node_modules needed for app)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public           ./public

# Uploads dir must be owned by nextjs so the app can write to it
RUN mkdir -p ./public/uploads && chown nextjs:nodejs ./public/uploads

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# `node server.js` is the standalone entrypoint generated by Next.js
CMD ["node", "server.js"]
